### ISSUE TITLE
SyntaxError: Unexpected token: < (line 274, file "Code")

### ISSUE THREAD

**Issue by CharlesChow** [saitei/crypto-sheets#46]
There is a syntax error when I tried to run the script and I saw the coinmarket API is shut down and using version 2. Is there is any way related?
![error](https://user-images.githubusercontent.com/10412963/43154002-715c5a0e-8fa5-11e8-9b78-38b645fe162e.jpg)

**Comment by LesterCovax** [comment]
It appears to be working for me still via the `v1` API.

![image](https://user-images.githubusercontent.com/34850610/43228701-484b617e-9030-11e8-9765-985402371b38.png)

Thank you for bringing that to my attention though 👏 that they're moving to a new API version (`v2`) and scrapping `v1`.  Looks like we have until November '18 to switch over 💩.  The `v1` API is still functioning though, which you can see by going here: https://api.coinmarketcap.com/v1/ticker/?limit=0

It's pulling in all the data, so I imagine your issue is a bad currency ID or formatting.  Check for commas / proper formatting in your currency list, and then compare the IDs in the list against those that the previous link spits out.  There may be a mismatch.

![image](https://user-images.githubusercontent.com/34850610/43228933-06f7257c-9031-11e8-9eb8-51125297849a.png)

I'll create an issue to upgrade the API in the coming months.  It will require a little work since they're now forcing you to grab 100 items at a time instead of doing a dump (which is what we're currently doing).

**Comment by LesterCovax** [comment]
The code I'm running may differ.  Are you looking at the master or dev
branch?  I don't think we've pushed anything up the pipeline in a while.

**Comment by CharlesChow** [comment]
https://www.reddit.com/r/cryptosheets/comments/8lnp3r/getting_an_error_when_attempting_to_run_getdata/
I still have that error after fix the ID and I saw it seem I cannot parse JSON data to the Google Sheets

**Comment by CharlesChow** [comment]
Solve it! the script suddenly running smoothly I think is the bad ID formatting after all

**Comment by zdavis28** [comment]
This is usually caused by CMC blacklisting some of google's servers. It will resolve itself after awhile

**Comment by p7b7** [comment]
I'm stuck in " var data = JSON.parse(json);" syntax error. How did you solve it?

**Comment by zdavis28** [comment]
It resolves itself eventually. any eta on v2?
